// web-angular/src/app/components/account/account.component.ts
import {Component} from '@angular/core';
import {FormGroup} from "@angular/forms";
import {FormlyFieldConfig, FormlyFormOptions} from "@ngx-formly/core";
import {AuthService} from "../../shared/auth-service";

@Component({
  selector: 'app-account',
  templateUrl: './account.component.html',
  styleUrls: ['./account.component.css']
})
export class AccountComponent {

  form = new FormGroup({});
  options: FormlyFormOptions = {};
  model = {
    username: '',
    password: ''
  };
  fields: FormlyFieldConfig[] = [
    {
      key: 'username',
      type: 'input',
      templateOptions: {
        label: 'Username',
        placeholder: 'Enter username',
        required: true
      }
    },
    {
      key: 'password',
      type: 'input',
      templateOptions: {
        label: 'Password',
        placeholder: 'Enter password',
        required: true,
        type: 'password'
      }
    }
  ];

  constructor(private authService: AuthService) {
  }

  submit(model) {
    this.authService.login(model);
  }

  isAuthenticated() {
    return this.authService.isAuthenticated();
  }

  logout() {
    this.authService.logout();
    window.location.reload();
  }
}

<div *ngIf="!isAuthenticated(); else logoutTemplate" class="account-container">
  <form [formGroup]="form" (ngSubmit)="submit(model)">
    <formly-form [form]="form" [fields]="fields" [options]="options" [model]="model"></formly-form>
    <button mat-flat-button color="primary" type="submit">Login</button>
  </form>
</div>

<ng-template #logoutTemplate>
  <button mat-flat-button color="primary" (click)="logout()">Logout</button>
</ng-template>

// web-vue/src/components/Account.vue
<template>
    <!--<div class="col-sm-4 col-sm-offset-4">-->
    <div>
        <div class="form-container" v-if="!auth.isAuthenticated()">
            <h2>Log in to your account</h2>
            <b-form @submit="login">
                <b-form-group id="usernameGroup"
                              label="Username:"
                              label-for="userName">
                    <b-form-input id="userName"
                                  type="text"
                                  v-model="credentials.username"
                                  required
                                  placeholder="Enter username">
                    </b-form-input>
                </b-form-group>

                <b-form-group id="passwordGroup"
                              label="Password:"
                              label-for="password">
                    <b-form-input id="password"
                                  type="password"
                                  v-model="credentials.password"
                                  required
                                  placeholder="Enter password">
                    </b-form-input>
                </b-form-group>

                <b-button type="button" v-on:click="login()" variant="primary">Login</b-button>
            </b-form>

        </div>
        <div class="form-container" v-else>
            <b-form @submit="logout">
                <b-button type="button" v-on:click="logout()" variant="primary">Logout</b-button>
            </b-form>
        </div>
    </div>

</template>

<script>
    import auth from './http/Auth'
    export default {
        data() {
            return {
                credentials: {
                    username: '',
                    password: ''
                },
                error: '',
                auth: auth,
            }
        },
        methods: {
            login() {
                var credentials = {
                    username: this.credentials.username,
                    password: this.credentials.password
                }
                auth.login(this, credentials)
                window.location.href = '/'
            },
            logout() {
                auth.logout()
                window.location.reload()
            }
        }

    }
</script>
